language: groovy
script: ./gradlew clean build  -PbintrayUserName= -PbintrayApiKey --info -PDO_NOT_RUN_DOXYGEN_EXE_TESTS=1
jdk:
 - oraclejdk7
 - oraclejdk8
 - openjdk7
os:
 - linux
 - osx
env: TERM=dumb
#after_success: ./gradlew coveralls -PbintrayUser= -PbintrayApiKey
